FROM debian:stretch

MAINTAINER Jay Davé <jay.dave@datadoghq.com>

ENV APP /app

RUN mkdir $APP
WORKDIR $APP

EXPOSE 8080

COPY requirements.txt .

RUN apt-get update -y && \
	apt-get -y install wkhtmltopdf-dbg && \
	apt-get -y install xvfb && \
	apt-get -y install python3 && \
	apt-get -y install python3-pip 

RUN pip3 install -r requirements.txt

RUN chmod 755 /usr/bin/wkhtmltopdf
RUN chmod 755 /usr/bin/wkhtmltoimage

COPY . .

#CMD tail -f /dev/null
CMD [ "uwsgi", "--ini", "app.ini" ]